import os
import argparse
import numpy as np
import SimpleITK as sitk
import nrrd
from scipy.ndimage import gaussian_filter
from typing import Tuple, List, Dict, Any, Optional

def generate_single_volume(volume_id: str, shape: Tuple[int, int, int], seed: int) -> Tuple[np.ndarray, np.ndarray, Dict[str, Any]]:
    """
    Generate a single synthetic 3D ultrasound volume and its segmentation mask.
    
    Args:
        volume_id (str): Identifier for the volume.
        shape (Tuple[int, int, int]): Shape of the volume as (Z, Y, X).
        seed (int): Random seed for reproducibility.
        
    Returns:
        Tuple[np.ndarray, np.ndarray, Dict[str, Any]]: image_array, label_array, metadata
    """
    np.random.seed(seed)
    
    # Generate background with Rayleigh noise to simulate ultrasound speckle
    background = np.random.rayleigh(scale=0.5, size=shape)
    
    # Generate random number of blobs (1 to 3) for the volume
    num_blobs = np.random.randint(1, 4)
    
    label_array = np.zeros(shape, dtype=np.uint8)
    image_array = background.copy()
    
    for i in range(num_blobs):
        # Blob properties
        blob_center = [np.random.randint(s // 4, 3 * s // 4) for s in shape]
        blob_radii = [np.random.randint(s // 10, s // 4) for s in shape]
        
        # Create grid
        z, y, x = np.ogrid[:shape[0], :shape[1], :shape[2]]
        
        # Ellipsoid equation: (z-cz)^2/rz^2 + (y-cy)^2/ry^2 + (x-cx)^2/rx^2 <= 1
        dist_sq = ((z - blob_center[0]) / blob_radii[0]) ** 2 + \
                  ((y - blob_center[1]) / blob_radii[1]) ** 2 + \
                  ((x - blob_center[2]) / blob_radii[2]) ** 2
        
        blob_mask = dist_sq <= 1
        
        # Add blob to label array (for simplicity, we'll assign class 1 to all blobs right now)
        label_array[blob_mask] = 1
        
        # Add blob intensity to image
        blob_intensity = np.random.uniform(0.5, 1.5)
        blob_signal = blob_mask.astype(float) * blob_intensity
        
        # Add some heterogeneity to the blob
        blob_signal *= np.random.rayleigh(scale=0.8, size=shape)
        
        image_array += blob_signal

    # Smooth the image slightly to make it look a bit more realistic
    image_array = gaussian_filter(image_array, sigma=1.0)
    
    # Normalize to [0, 255] for uint8 storage
    image_array = (image_array - np.min(image_array)) / (np.max(image_array) - np.min(image_array) + 1e-8)
    image_array = (image_array * 255).astype(np.uint8)
    
    metadata = {
        "spacing": (1.0, 1.0, 1.0),  # Example spacing X, Y, Z
        "origin": (0.0, 0.0, 0.0),
        "direction": np.eye(3).flatten().tolist()
    }
    
    return image_array, label_array, metadata

def write_mha(filepath: str, image_array: np.ndarray, metadata: Dict[str, Any]):
    """
    Write image array to a MetaImage (.mha) file using SimpleITK.
    """
    # sitk.GetImageFromArray expects array in Z, Y, X order, which matches our generation
    sitk_img = sitk.GetImageFromArray(image_array)
    sitk_img.SetSpacing(metadata.get("spacing", (1.0, 1.0, 1.0)))
    sitk_img.SetOrigin(metadata.get("origin", (0.0, 0.0, 0.0)))
    if "direction" in metadata:
        sitk_img.SetDirection(metadata["direction"])
        
    sitk.WriteImage(sitk_img, filepath)

def write_seg_nrrd(filepath: str, label_array: np.ndarray, metadata: Dict[str, Any]):
    """
    Write label array to a 3D Slicer segmentation (.seg.nrrd) file using pynrrd.
    """
    # In pynrrd, the array shape should typically match the spatial domain [x, y, z]
    label_array_t = np.transpose(label_array, (2, 1, 0))
    
    # Create 3D Slicer segment metadata headers
    header = {
        'type': 'unsigned char',
        'dimension': 3,
        'space': 'left-posterior-superior',
        'sizes': list(label_array_t.shape),
        'space directions': [[1, 0, 0], [0, 1, 0], [0, 0, 1]], # Assuming 1mm spacing
        'kinds': ['domain', 'domain', 'domain'],
        'endian': 'little',
        'encoding': 'gzip',
        'space origin': [0, 0, 0],
        'Segmentation_MasterRepresentation': 'Binary labelmap',
        'Segmentation_ContainedRepresentationNames': 'Binary labelmap|',
        'Segment0_ID': 'Segment_1',
        'Segment0_Name': 'Organ',
        'Segment0_Color': '0.5 0.5 0.5',
        'Segment0_ColorAutoGenerated': '1',
        'Segment0_Extent': f'0 {label_array_t.shape[0]-1} 0 {label_array_t.shape[1]-1} 0 {label_array_t.shape[2]-1}',
        'Segment0_LabelValue': '1',
        'Segment0_Layer': '0',
    }
    
    nrrd.write(filepath, label_array_t, header=header)

def generate_synthetic_dataset(
    output_dir: str,
    num_volumes: int = 20,
    num_labeled: int = 5,
    seed: int = 42,
    image_size: Optional[Tuple[int, int, int]] = None
) -> List[str]:
    """
    Generate synthetic dataset with labeled and unlabeled volumes (V9-2, V9-3 fix).
    """
    np.random.seed(seed)

    images_dir = os.path.join(output_dir, 'images')
    labels_dir = os.path.join(output_dir, 'labels')

    os.makedirs(images_dir, exist_ok=True)
    os.makedirs(labels_dir, exist_ok=True)

    volume_ids = []

    for i in range(num_volumes):
        # Patient-prefix volume ID format (e.g. US000_v1) so split('_')[0] yields US000 (V9-3 fix)
        volume_id = f"US{i:03d}_v1"
        volume_ids.append(volume_id)

        if image_size is not None:
            shape = image_size
        else:
            # Random dimensions between 128x128x80 and 256x256x200 (Z, Y, X)
            z = np.random.randint(80, 200)
            y = np.random.randint(128, 256)
            x = np.random.randint(128, 256)
            shape = (z, y, x)

        vol_seed = seed + i
        image_array, label_array, metadata = generate_single_volume(volume_id, shape, vol_seed)

        img_path = os.path.join(images_dir, f"{volume_id}.mha")
        write_mha(img_path, image_array, metadata)

        # Only save label for the first num_labeled volumes
        if i < num_labeled:
            lbl_path = os.path.join(labels_dir, f"{volume_id}.seg.nrrd")
            write_seg_nrrd(lbl_path, label_array, metadata)

        print(f"Generated {volume_id} with shape {shape}")

    return volume_ids

def main():
    parser = argparse.ArgumentParser(description="Generate synthetic 3D ultrasound dataset.")
    parser.add_argument("--output", type=str, required=True, help="Output directory for the dataset")
    parser.add_argument("--num-volumes", type=int, default=20, help="Total number of volumes to generate")
    parser.add_argument("--num-labeled", type=int, default=5, help="Number of labeled volumes (must be <= num-volumes)")
    parser.add_argument("--seed", type=int, default=42, help="Random seed")
    
    args = parser.parse_args()
    
    if args.num_labeled > args.num_volumes:
        raise ValueError("Number of labeled volumes cannot exceed total number of volumes.")
        
    print(f"Generating synthetic dataset in {args.output}...")
    generate_synthetic_dataset(args.output, args.num_volumes, args.num_labeled, args.seed)
    print("Dataset generation complete.")

if __name__ == "__main__":
    main()
